### ISSUE TITLE
Mob_Acc_Subscription: Help (?) missing on the top header.

### ISSUE THREAD

**Issue by nadusouza** [ajency/cibil-dashboard-paid#16]
Tested on Mobile iOS

Ref FIGMA : Top Header section has a white (?)
![image](https://user-images.githubusercontent.com/118731697/203390124-c869c13f-540f-4859-a0ce-01e57faf6a5b.png)

on the mobile browser, it is missing.
![IMG_1546](https://user-images.githubusercontent.com/118731697/203390203-32f0b7c1-1cd2-43b2-b035-e313b708a80a.jpeg)

**Comment by siddeshKalangutkar** [comment]
"How it works" feature is only available for the home page
