### ISSUE TITLE
Mob_Score Simulator: the meter pointer doesn't point to the right colour code.

### ISSUE THREAD

**Issue by nadusouza** [ajency/cibil-dashboard-paid#20]
Tested on Mobile iOS

Ref FIGMA :
The pointer points on orange for the value 720
![image](https://user-images.githubusercontent.com/118731697/203397249-d31c9ba2-b61a-4b9e-aaba-b97ae543cff9.png)

on the mobile browser,
The pointer points on yellowfor the value 720
![IMG_1553](https://user-images.githubusercontent.com/118731697/203397340-4899e099-155e-4b49-a82e-b3aeacb39116.jpeg)

**Comment by MamataNivajekar** [comment]
@nadusouza The pointer should point to the yellow as per the formula
