### ISSUE TITLE
Mob_Score Simulator: Add Scenario

### ISSUE THREAD

**Issue by nadusouza** [ajency/cibil-dashboard-paid#21]
Tested on Mobile iOS

part 1: Alignment of "Add a new loan....., clear outstanding....(active accounts), clear outstanding....(active credit cards). In the Prototype, these sentences appear on a single line
part 2: " Add New  Enquiry" missing

on FIGMA:
![image](https://user-images.githubusercontent.com/118731697/203398015-8cd5647c-a988-4205-8fee-f6d98b6270c1.png)

on the mobile browser,
![IMG_1555](https://user-images.githubusercontent.com/118731697/203398076-7957c052-2d56-4fbe-9e6a-e79ee3735500.jpeg)

**Comment by MamataNivajekar** [comment]
@nadusouza 
part 1:  The sentences/text lines will go to the next line depending on the device's width.
