### ISSUE TITLE
Mob_Score Simulator: FAQs questions are not the same

### ISSUE THREAD

**Issue by nadusouza** [ajency/cibil-dashboard-paid#22]
Tested on Mobile iOS
Questionnaire isn't the same on the prototype and the answer text also varies.

on FIGMA :
![image](https://user-images.githubusercontent.com/118731697/203398671-0a2f51ac-07e3-4716-b11a-28972988e56b.png)

on the mobile browser,
![IMG_1556](https://user-images.githubusercontent.com/118731697/203398587-674b4f32-e4be-49da-8b8b-d4a0ea2208d1.jpeg)

**Comment by MamataNivajekar** [comment]
@nadusouza FAQs are added as per the content doc shared by the client.
