### ISSUE TITLE
Mob_Upgrade Plan: Show All Plans appear several times

### ISSUE THREAD

**Issue by nadusouza** [ajency/cibil-dashboard-paid#41]
Tested on Mobile OS

The link "Show All Plans" keeps multiplying every time we scroll up and down.
![IMG_1558](https://user-images.githubusercontent.com/118731697/203545435-50102258-792a-47ea-915a-f4c7cbc4a3f8.jpeg)

**Comment by saieshv** [comment]
Fixed on safari desktop

**Comment by saieshv** [comment]
@nadusouza  Please check on the IOS device

**Comment by nadusouza** [comment]
fixed on iOS
