### ISSUE TITLE
Mobile_Upgrade Plan: "Save 75" section is overlapping the border line

### ISSUE THREAD

**Issue by nadusouza** [ajency/cibil-dashboard-paid#44]
Tested on iOS

Ref FIGMA: The "Save 75%" isn't overlapping the border here
![image](https://user-images.githubusercontent.com/118731697/203704323-8a5e8ec3-29a8-4791-900a-eb52e36d616e.png)
![image](https://user-images.githubusercontent.com/118731697/203705625-4b499f85-e211-4da9-8f25-63a8eb9289d2.png)

On the Mobile browser, It is overlapping the border.
In the same section, a line is missing and the column border has a small line break. I tried to attach a screenshot. 
![IMG_1570](https://user-images.githubusercontent.com/118731697/203704549-33c44710-ada8-472e-b316-8884d3cb7797.jpeg)
![IMG_1572](https://user-images.githubusercontent.com/118731697/203705540-798e3431-b67d-477a-ab0c-816f47ffc8d5.jpeg)

**Comment by MamataNivajekar** [comment]
@nadusouza 
In the same section, a line is missing and the column border has a small line break. I tried to attach a screenshot. --> Invalid. Unable to replicate the issue. 
Tested on, Device: iPhone X, Version: 15

![image](https://user-images.githubusercontent.com/81617777/203714731-9485c22d-ae33-4b8f-bb67-3dcfa64ed807.png)

**Comment by nadusouza** [comment]
fixed. noted that the other scenarios cant be replicated.
