### ISSUE TITLE
M_Alerts _ Spacing on subheading 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard-paid#5]
- Spacing currently below the icon & subheading is 10px.
this is to be kept 20px on all pages also font-weight is to be kept medium. similar to desktop UI font-weight

<img width="342" alt="Screenshot 2022-11-21 at 3 59 19 PM" src="https://user-images.githubusercontent.com/81156455/203028024-51290c3f-a8ad-4373-9beb-4b84a08db43f.png">

**Comment by MamataNivajekar** [comment]
Properties added as per the Figma design.
