### ISSUE TITLE
D&M_ Overview : Where you stand - Input Field 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard-paid#56]
- "Monthly Income" Input field is to be kept in currency format with commas similar to what we did for input fields on Scenarios 

Ref. img from live site
<img width="1091" alt="Screenshot 2022-11-24 at 1 10 48 PM" src="https://user-images.githubusercontent.com/81156455/203722701-8a1f44f7-043a-42a6-94d1-f19b269b531a.png">

Example : 
<img width="321" alt="Screenshot 2022-11-24 at 1 14 06 PM" src="https://user-images.githubusercontent.com/81156455/203723333-f6227f79-bc9b-402e-9a3b-a572f3aeeed6.png">

**Comment by KaranAjency** [comment]
Duplicate issue. Fixed.
