### ISSUE TITLE
M_Overview : Where you stand - Color band arrow issue 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard-paid#61]
- Arrow currently is off-center this is to be kept centered

Ref. from live site
 
![Group 27625 (1)](https://user-images.githubusercontent.com/81156455/203774098-d3dd608c-9417-47fe-be29-5233e0926761.jpg)

**Comment by KaranAjency** [comment]
Fixed

**Comment by saieshv** [comment]
Fixed
