### ISSUE TITLE
M_Overview : Score History padding issue

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard-paid#64]
Padding is to be kept at 20px, currently it's on 25px. 

<img width="795" alt="Screenshot 2022-11-24 at 5 25 53 PM" src="https://user-images.githubusercontent.com/81156455/203778827-cf66002e-0472-4cfd-9e42-e9f982c74cbc.png">

**Comment by saieshv** [comment]
Fixed

**Comment by KaranAjency** [comment]
Fixed with 20px.
