### ISSUE TITLE
M_ Overview : Where you stand - Drop down z-index issue 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard-paid#65]
- dropdown list of 1st is appearing below the 2nd dropdown (both the dropdowns when in the opened state are overlapping)

Ref. image 
<img width="412" alt="Screenshot 2022-11-24 at 5 31 27 PM" src="https://user-images.githubusercontent.com/81156455/203779938-0bf6c6f4-a0dd-4d08-b83c-b711e19daa4f.png">

**Comment by KaranAjency** [comment]
Fixed

**Comment by saieshv** [comment]
Fixed.
