### ISSUE TITLE
open accounts representation

### ISSUE THREAD

**Issue by Saee1799** [ajency/cibil-dashboard-paid#82]
The accounts should be separated by a box. The box border should have #ACACAC as its stroke color
Every account should have the Member name, Account type, Account number and ownership labels

![image](https://user-images.githubusercontent.com/96518669/218089057-38367766-2a3b-4333-b9ef-8dfed094e2b7.png)

This is how the design should look
![image](https://user-images.githubusercontent.com/96518669/218089800-d6204a17-db5b-4d26-a7fb-5f15ae1a1f1d.png)

**Comment by EktaNaik** [comment]
Fixed and verified.
