### ISSUE TITLE
issue with the payment status under open accounts section

### ISSUE THREAD

**Issue by Saee1799** [ajency/cibil-dashboard-paid#83]
Payment status should be in bold. Also there is something weird happening with the design, when I click on payment status it turns into bold. 

![image](https://user-images.githubusercontent.com/96518669/218090026-0edc0c04-aaa8-4a17-b4f1-e1d3e0757ac6.png)

https://user-images.githubusercontent.com/96518669/218090372-bbaf679f-1bbf-4336-b832-ed6e35fcc993.mp4

**Comment by EktaNaik** [comment]
Fixed and verified.
