### ISSUE TITLE
Mobile_ Credit Summary: Count of Late Payments -text of tabs in single line

### ISSUE THREAD

**Issue by nadusouza** [ajency/cibil-dashboard-paid#9]
Testing on IPhone browser
Text on the tab should be in a single line (Last 12 months and Last 36 months) as in the prototype.

On the Mobile browser,
Shows in double line
![IMG_1535](https://user-images.githubusercontent.com/118731697/203059869-15ab38a7-32aa-427f-831a-a5898a133841.jpeg)

**Comment by nadusouza** [comment]
The issue still persists.
If i reduce my safari browser size to 85%, the text is in a single line.
But if its 100%, then its on 2 lines

**Comment by saieshv** [comment]
@siddeshKalangutkar 

can we keep both the "tab nav links" as 2 liners for breakpoints below 400px?
currently one is single liner & 2nd text goes on line 2

<img width="386" alt="Screenshot 2022-11-22 at 10 51 46 AM" src="https://user-images.githubusercontent.com/81156455/203228525-f449e315-3409-4050-ae9f-86889533cec1.png">

**Comment by saieshv** [comment]
Fixed
